const fonts = [

    "Arial",
    "Arial Black",
    "Comic Sans MS",
    "Courier New",
    "Georgia",
    "Impact",
    "Lucida Console",
    "Lucida Sans Unicode",
    "Palatino Linotype",
    "Tahoma",
    "Times New Roman",
    "Trebuchet MS",
    "Verdana",
    "Arial Narrow",
    "Arial Rounded MT Bold",
    "Courier",
    "Geneva",
    "Helvetica",
    "Impact",
    "Monaco",
    "Optima",
    "Garamond",
    "Brush Script MT",
    "Copperplate",
    "Papyrus",
    "Futura",
    "Baskerville",
    "Big Caslon",
    "Bodoni MT",
    "Book Antiqua",
    "Brush Script Std",
    "Didot",
    "Goudy Old Style",
    "Hoefler Text",
    "Lucida Bright",
    "Perpetua",
    "Rockwell",
    "American Typewriter",
    "Andale Mono",
    "Courier New Bold",
    "Courier New Italic",
    "Courier New Bold Italic",
    "Lucida Sans",
    "Lucida Grande",
    "Monaco",
    "Zapf Chancery",
    "Zapfino",
    "Georgia Bold",
    "Georgia Italic",
    "Georgia Bold Italic",
    "Times New Roman Bold",
    "Times New Roman Italic",
    "Times New Roman Bold Italic",
    "Verdana Bold",
    "Verdana Italic",
    "Verdana Bold Italic",
    "Trebuchet MS Bold",
    "Trebuchet MS Italic",
    "Trebuchet MS Bold Italic",
    "Arial Bold",
    "Arial Italic",
    "Arial Bold Italic"

];

export default fonts;


